name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request_target:
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - name: Format.
        run: make format
      - name: Linting & vetting.
        run: make lint-ci

  Testing_and_building:
    runs-on: ubuntu-latest
    env:
      env: ${{ secrets.env }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Running tests
        run: make test-ci
