name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Format.
        run: make format
      - name: Linting & vetting.
        run: make lint

  Testing_and_building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Running tests
        run: make test